# Generated by Django 5.1.1 on 2024-09-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_corner_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corner",
            options={"verbose_name": "Corner", "verbose_name_plural": "Corners"},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedbacks"},
        ),
        migrations.AlterModelOptions(
            name="measurement",
            options={"verbose_name": "Messung", "verbose_name_plural": "Messungen"},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"verbose_name": "Sensor", "verbose_name_plural": "Sensoren"},
        ),
        migrations.AlterField(
            model_name="corner",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="corner",
            name="lat",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name="Breitengrad"),
        ),
        migrations.AlterField(
            model_name="corner",
            name="lon",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name="Längengrad"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="loudness",
            field=models.CharField(
                choices=[
                    ("Sehr laut", "Sehr laut"),
                    ("Laut", "Laut"),
                    ("neutral", "Neutral"),
                    ("leise", "Leise"),
                    ("Sehr leise", "Sehr leise"),
                ],
                verbose_name="Lautstärke",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(verbose_name="Nachricht"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(max_length=100, verbose_name="Thema"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="prediction",
            field=models.FloatField(verbose_name="Vorhersage"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="value",
            field=models.IntegerField(verbose_name="Wert (dBA)"),
        ),
    ]
