# Generated by Django 5.1.1 on 2024-09-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_measurement_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corner",
            name="lat",
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True, verbose_name="Breitengrad"),
        ),
        migrations.AlterField(
            model_name="corner",
            name="lon",
            field=models.DecimalField(decimal_places=18, max_digits=20, null=True, verbose_name="Längengrad"),
        ),
    ]
