# Generated by Django 5.1.1 on 2024-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_corner_lat_alter_corner_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
