# Generated by Django 5.1.1 on 2024-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_measurement_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
